export const GET_PHOTOS_REQUESTED = "GET_PHOTOS_REQUESTED";
export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS";

export const GET_PHOTO_REQUESTED = "GET_PHOTO_REQUESTED";
export const GET_PHOTO_SUCCESS = "GET_PHOTO_SUCCESS";

export const SEARCH_PHOTO_SUCCESS = "SEARCH_PHOTO_SUCCESS";
export const SEARCH_PHOTO_REQUESTED = "SEARCH_PHOTO_REQUESTED";

export const CHANGE_MODAL = "CHANGE_MODAL";
